#!/usr/bin/env python3
"""Aggregate system-level tracking analysis across a project folder.

Reads per-video ``system_analysis`` outputs generated by
``scripts/system_tracking_analysis.py`` and writes project-level CSV tables plus
PNG/PDF/SVG figures. By default outputs are written to
``<project_dir>/system_analysis``.
"""

from __future__ import annotations

import argparse
import math
import sys
from pathlib import Path
from typing import Any

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from pandas.errors import EmptyDataError

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT / "scripts") not in sys.path:
    sys.path.insert(0, str(REPO_ROOT / "scripts"))

from system_tracking_analysis import (  # noqa: E402
    FIG_FORMATS,
    NEAR_BBOX_GAP_THRESHOLD_NORM,
    ZERO_BBOX_GAP_EPS,
    _add_sig_bracket,
    _compare_samples,
    run as run_video_analysis,
)


SUMMARY_FILE = "summary_metrics.csv"
LABELING_FILE = "labeling_timing.csv"
THROUGHPUT_FILE = "throughput_distribution.csv"


def _save_fig(fig: plt.Figure, output_dir: Path, stem: str) -> None:
    for fmt in FIG_FORMATS:
        fig.savefig(output_dir / f"{stem}.{fmt}", bbox_inches="tight", dpi=220)
    plt.close(fig)


def _coerce_value(value: Any) -> Any:
    if pd.isna(value):
        return np.nan
    if isinstance(value, str):
        stripped = value.strip()
        if not stripped:
            return ""
        try:
            return float(stripped)
        except ValueError:
            return stripped
    return value


def _read_summary_wide(path: Path, video_dir: Path) -> dict[str, Any]:
    df = pd.read_csv(path)
    row: dict[str, Any] = {"video_dir": str(video_dir), "video_folder": video_dir.name}
    for _, r in df.iterrows():
        row[str(r["metric"])] = _coerce_value(r["value"])
    return row


def _read_csv_or_empty(path: Path) -> pd.DataFrame:
    try:
        return pd.read_csv(path)
    except EmptyDataError:
        return pd.DataFrame()


def _discover_video_dirs(project_dir: Path) -> list[Path]:
    videos_dir = project_dir / "videos"
    if not videos_dir.is_dir():
        raise FileNotFoundError(f"Missing videos directory: {videos_dir}")
    return sorted(p for p in videos_dir.iterdir() if p.is_dir() and p.name.endswith(".mp4"))


def _ensure_per_video_outputs(video_dirs: list[Path], refresh: bool) -> None:
    required = (SUMMARY_FILE, LABELING_FILE, THROUGHPUT_FILE)
    for video_dir in video_dirs:
        out = video_dir / "system_analysis"
        missing = any(not (out / name).is_file() for name in required)
        if refresh or missing:
            run_video_analysis(str(video_dir))


def load_project_tables(project_dir: Path, refresh: bool = False) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    video_dirs = _discover_video_dirs(project_dir)
    _ensure_per_video_outputs(video_dirs, refresh=refresh)

    summary_rows: list[dict[str, Any]] = []
    labeling_tables: list[pd.DataFrame] = []
    throughput_tables: list[pd.DataFrame] = []

    for video_dir in video_dirs:
        out = video_dir / "system_analysis"
        summary_path = out / SUMMARY_FILE
        if not summary_path.is_file():
            continue
        summary = _read_summary_wide(summary_path, video_dir)
        video_id = str(summary.get("video_id") or video_dir.name.split("_", 1)[0])
        video_name = str(summary.get("video_name") or video_dir.name)
        summary_rows.append(summary)

        labeling_path = out / LABELING_FILE
        if labeling_path.is_file():
            ldf = _read_csv_or_empty(labeling_path)
            if not ldf.empty:
                ldf.insert(0, "video_name", video_name)
                ldf.insert(0, "video_id", video_id)
                labeling_tables.append(ldf)

        throughput_path = out / THROUGHPUT_FILE
        if throughput_path.is_file():
            tdf = _read_csv_or_empty(throughput_path)
            if not tdf.empty:
                tdf.insert(0, "video_name", video_name)
                tdf.insert(0, "video_id", video_id)
                throughput_tables.append(tdf)

    summary_df = pd.DataFrame(summary_rows)
    labeling_df = pd.concat(labeling_tables, ignore_index=True) if labeling_tables else pd.DataFrame()
    throughput_df = pd.concat(throughput_tables, ignore_index=True) if throughput_tables else pd.DataFrame()
    return summary_df, labeling_df, throughput_df


def _numeric_summary(values: pd.Series) -> dict[str, float]:
    clean = pd.to_numeric(values, errors="coerce").replace([np.inf, -np.inf], np.nan).dropna()
    if clean.empty:
        return {"n": 0, "mean": math.nan, "sd": math.nan, "q25": math.nan, "median": math.nan, "q75": math.nan, "min": math.nan, "max": math.nan}
    return {
        "n": int(clean.size),
        "mean": float(clean.mean()),
        "sd": float(clean.std(ddof=1)) if clean.size > 1 else 0.0,
        "q25": float(clean.quantile(0.25)),
        "median": float(clean.quantile(0.50)),
        "q75": float(clean.quantile(0.75)),
        "min": float(clean.min()),
        "max": float(clean.max()),
    }


def _duration_group_rows(labeling_df: pd.DataFrame) -> list[dict[str, Any]]:
    if labeling_df.empty or "min_bbox_edge_gap_norm" not in labeling_df:
        return []
    gaps = pd.to_numeric(labeling_df["min_bbox_edge_gap_norm"], errors="coerce")
    durations = pd.to_numeric(labeling_df["duration_s"], errors="coerce")
    valid = gaps.notna() & durations.notna()
    gaps = gaps[valid]
    durations = durations[valid]
    groups = [
        ("pooled_labeling_duration_overlap_bbox_s", gaps <= ZERO_BBOX_GAP_EPS),
        ("pooled_labeling_duration_nonzero_bbox_gap_s", gaps > ZERO_BBOX_GAP_EPS),
        ("pooled_labeling_duration_close_bbox_gap_lt_0p02_s", gaps < NEAR_BBOX_GAP_THRESHOLD_NORM),
        ("pooled_labeling_duration_separated_bbox_gap_gt_0p02_s", gaps > NEAR_BBOX_GAP_THRESHOLD_NORM),
    ]
    return [{"metric": name, **_numeric_summary(durations[mask])} for name, mask in groups]


def _labeling_group_comparisons(labeling_df: pd.DataFrame) -> pd.DataFrame:
    if labeling_df.empty or "min_bbox_edge_gap_norm" not in labeling_df:
        return pd.DataFrame()
    gaps = pd.to_numeric(labeling_df["min_bbox_edge_gap_norm"], errors="coerce")
    durations = pd.to_numeric(labeling_df["duration_s"], errors="coerce")
    valid = gaps.notna() & durations.notna()
    gaps = gaps[valid]
    durations = durations[valid]

    comparisons = [
        (
            "bbox_overlap_0_vs_gt0",
            "0",
            durations[gaps <= ZERO_BBOX_GAP_EPS],
            ">0",
            durations[gaps > ZERO_BBOX_GAP_EPS],
        ),
        (
            "bbox_gap_lt0p02_vs_gt0p02",
            "<0.02",
            durations[gaps < NEAR_BBOX_GAP_THRESHOLD_NORM],
            ">0.02",
            durations[gaps > NEAR_BBOX_GAP_THRESHOLD_NORM],
        ),
    ]
    rows = []
    for name, label_a, a, label_b, b in comparisons:
        stats_a = _numeric_summary(a)
        stats_b = _numeric_summary(b)
        pvals = _compare_samples(a.to_numpy(dtype=float), b.to_numpy(dtype=float))
        rows.append(
            {
                "comparison": name,
                "group_a": label_a,
                "n_a": stats_a["n"],
                "mean_a_s": stats_a["mean"],
                "std_a_s": stats_a["sd"],
                "median_a_s": stats_a["median"],
                "group_b": label_b,
                "n_b": stats_b["n"],
                "mean_b_s": stats_b["mean"],
                "std_b_s": stats_b["sd"],
                "median_b_s": stats_b["median"],
                "welch_ttest_p": pvals["welch_p"],
                "mannwhitney_u_p": pvals["mannwhitney_p"],
            }
        )
    return pd.DataFrame(rows)


def write_aggregate_tables(
    summary_df: pd.DataFrame,
    labeling_df: pd.DataFrame,
    throughput_df: pd.DataFrame,
    output_dir: Path,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    output_dir.mkdir(parents=True, exist_ok=True)

    summary_df.to_csv(output_dir / "per_video_system_metrics.csv", index=False)
    labeling_df.to_csv(output_dir / "pooled_labeling_timing.csv", index=False)
    throughput_df.to_csv(output_dir / "pooled_throughput_distribution.csv", index=False)

    metrics = [
        "num_frames",
        "saved_tracking_frames",
        "anchor_frame_count",
        "frames_per_anchor_label",
        "saved_tracking_frames_per_anchor_label",
        "tracking_coverage_of_video",
        "labeling_duration_median_s",
        "labeling_min_bbox_edge_gap_median_norm",
        "labeling_min_bbox_center_distance_median_norm",
        "labeling_duration_vs_edge_gap_spearman",
        "labeling_duration_vs_center_distance_spearman",
        "labeling_duration_median_overlap_bbox_s",
        "labeling_duration_median_nonzero_bbox_gap_s",
        "labeling_duration_median_close_bbox_gap_lt_0p02_s",
        "labeling_duration_median_separated_bbox_gap_gt_0p02_s",
        "mean_saved_frame_throughput_fps",
        "save_burst_throughput_q25_fps",
        "save_burst_throughput_median_fps",
        "save_burst_throughput_q75_fps",
        "processing_seconds_per_video_second",
    ]
    rows = []
    for metric in metrics:
        if metric not in summary_df:
            continue
        stats = _numeric_summary(summary_df[metric])
        rows.append({"metric": metric, **stats})

    if not labeling_df.empty and "duration_s" in labeling_df:
        rows.append({"metric": "pooled_anchor_labeling_duration_s", **_numeric_summary(labeling_df["duration_s"])})
    if not labeling_df.empty and "min_bbox_edge_gap_norm" in labeling_df:
        rows.append({"metric": "pooled_nearest_bbox_edge_gap_norm", **_numeric_summary(labeling_df["min_bbox_edge_gap_norm"])})
        rows.extend(_duration_group_rows(labeling_df))
        _labeling_group_comparisons(labeling_df).to_csv(output_dir / "labeling_group_comparisons.csv", index=False)
    else:
        pd.DataFrame().to_csv(output_dir / "labeling_group_comparisons.csv", index=False)
    if not throughput_df.empty and "instantaneous_saved_fps" in throughput_df:
        rows.append({"metric": "pooled_save_burst_throughput_fps", **_numeric_summary(throughput_df["instantaneous_saved_fps"])})

    aggregate_df = pd.DataFrame(rows)
    aggregate_df.to_csv(output_dir / "aggregate_summary_metrics.csv", index=False)

    per_video_dist = []
    if not labeling_df.empty:
        for vid, group in labeling_df.groupby("video_id"):
            video_name = str(group["video_name"].iloc[0])
            stats = _numeric_summary(group["duration_s"])
            per_video_dist.append({"video_id": vid, "video_name": video_name, "distribution": "labeling_duration_s", **stats})
            if "min_bbox_edge_gap_norm" in group:
                stats = _numeric_summary(group["min_bbox_edge_gap_norm"])
                per_video_dist.append({"video_id": vid, "video_name": video_name, "distribution": "nearest_bbox_edge_gap_norm", **stats})
    if not throughput_df.empty:
        for vid, group in throughput_df.groupby("video_id"):
            video_name = str(group["video_name"].iloc[0])
            stats = _numeric_summary(group["instantaneous_saved_fps"])
            per_video_dist.append({"video_id": vid, "video_name": video_name, "distribution": "save_burst_throughput_fps", **stats})
    per_video_dist_df = pd.DataFrame(per_video_dist)
    per_video_dist_df.to_csv(output_dir / "per_video_distribution_summaries.csv", index=False)
    return aggregate_df, per_video_dist_df


def plot_labeling_aggregate(summary_df: pd.DataFrame, labeling_df: pd.DataFrame, output_dir: Path) -> None:
    fig, axes = plt.subplots(2, 2, figsize=(12.0, 8.0))
    axes = axes.ravel()

    if not labeling_df.empty:
        durations = labeling_df["duration_s"].dropna().to_numpy(dtype=float)
        display_limit = float(np.percentile(durations, 99)) if durations.size else math.nan
        central_durations = durations[durations <= display_limit] if durations.size else durations
        clipped_count = int(durations.size - central_durations.size)
        video_medians = summary_df["labeling_duration_median_s"].dropna().astype(float).to_numpy()

        ax = axes[0]
        ax.violinplot(central_durations, positions=[1], widths=0.7, showmedians=False)
        ax.boxplot(central_durations, positions=[1], widths=0.18, showfliers=True, medianprops={"color": "#E15759", "linewidth": 2})
        ax.set_xticks([1])
        ax.set_xticklabels(["All anchor labels"])
        ax.set_ylabel("Duration (s)")
        ax.set_title(f"Pooled durations, central 99% (n={len(central_durations):,}; clipped {clipped_count})")
        ax.grid(True, axis="y", alpha=0.25)

        ax = axes[1]
        bins = min(50, max(10, int(np.sqrt(len(central_durations)))))
        ax.hist(central_durations, bins=bins, color="#F28E2B", alpha=0.78, edgecolor="white")
        for q, label, style in zip(np.percentile(durations, [25, 50, 75]), ["25th", "median", "75th"], [":", "-", ":"]):
            ax.axvline(q, color="#E15759" if label == "median" else "#555555", linestyle=style, linewidth=1.8 if label == "median" else 1.2)
        ax.set_xlabel("Duration (s)")
        ax.set_ylabel("Anchor count")
        ax.set_title("Pooled duration histogram, central 99%")
        ax.grid(True, axis="y", alpha=0.25)

        ax = axes[2]
        if video_medians.size:
            ax.boxplot(video_medians, vert=True, widths=0.35, patch_artist=True,
                       boxprops={"facecolor": "#D7E6F5", "color": "#4C78A8"},
                       medianprops={"color": "#E15759", "linewidth": 2})
            ax.scatter(np.ones_like(video_medians) + np.linspace(-0.09, 0.09, len(video_medians)), video_medians,
                       s=24, color="#4C78A8", alpha=0.75)
        ax.set_xticks([1])
        ax.set_xticklabels(["Video medians"])
        ax.set_ylabel("Median duration (s)")
        ax.set_title("Distribution of per-video median labeling times")
        ax.grid(True, axis="y", alpha=0.25)

        ax = axes[3]
        if "min_bbox_edge_gap_norm" in labeling_df:
            _plot_distance_group_comparison(ax, labeling_df, display_limit=display_limit)
        else:
            ax.text(0.5, 0.5, "No nearest bbox gap data found", ha="center", va="center")
            ax.set_axis_off()
    else:
        for ax in axes:
            ax.text(0.5, 0.5, "No labeling timing data found", ha="center", va="center")
            ax.set_axis_off()

    fig.suptitle("Project-Level Labeling Efficiency", y=1.01, fontsize=13)
    fig.tight_layout()
    _save_fig(fig, output_dir, "aggregate_labeling_efficiency")


def _plot_distance_group_comparison(ax: plt.Axes, labeling_df: pd.DataFrame, display_limit: float | None = None) -> None:
    all_gaps = pd.to_numeric(labeling_df["min_bbox_edge_gap_norm"], errors="coerce")
    all_durations = pd.to_numeric(labeling_df["duration_s"], errors="coerce")
    all_valid = all_gaps.notna() & all_durations.notna()
    full_gaps = all_gaps[all_valid]
    full_durations = all_durations[all_valid]
    valid = all_valid.copy()
    if display_limit is not None and not math.isnan(display_limit):
        valid &= all_durations <= display_limit
    gaps = all_gaps[valid]
    durations = all_durations[valid]

    groups = [
        ("0", durations[gaps <= ZERO_BBOX_GAP_EPS].to_numpy(dtype=float), "#4C78A8"),
        (">0", durations[gaps > ZERO_BBOX_GAP_EPS].to_numpy(dtype=float), "#4C78A8"),
        ("<0.02", durations[gaps < NEAR_BBOX_GAP_THRESHOLD_NORM].to_numpy(dtype=float), "#59A14F"),
        (">0.02", durations[gaps > NEAR_BBOX_GAP_THRESHOLD_NORM].to_numpy(dtype=float), "#59A14F"),
    ]
    data = [vals for _, vals, _ in groups if vals.size]
    positions = [i + 1 for i, (_, vals, _) in enumerate(groups) if vals.size]
    labels = [f"{label}\n(n={len(vals):,})" for label, vals, _ in groups if vals.size]
    colors = [color for _, vals, color in groups if vals.size]
    if not data:
        ax.text(0.5, 0.5, "No nearest bbox gap data found", ha="center", va="center")
        ax.set_axis_off()
        return
    bp = ax.boxplot(data, positions=positions, widths=0.55, patch_artist=True, showfliers=True,
                    medianprops={"color": "#E15759", "linewidth": 2})
    for patch, color in zip(bp["boxes"], colors):
        patch.set_facecolor(color)
        patch.set_alpha(0.25)
        patch.set_edgecolor(color)
    ax.axvline(2.5, color="#999999", linewidth=1, linestyle=":")
    ax.set_xticks(positions)
    ax.set_xticklabels(labels)
    ax.set_xlabel("Nearest bbox edge gap / frame diagonal")
    ax.set_ylabel("Labeling duration (s)")
    ax.set_title("Duration by bbox overlap and close-separation bins")
    ax.grid(True, axis="y", alpha=0.25)
    y_base = max(np.nanmax(vals) for vals in data if vals.size)
    y_span = max(ax.get_ylim()[1] - ax.get_ylim()[0], 1.0)
    overlap = full_durations[full_gaps <= ZERO_BBOX_GAP_EPS].to_numpy(dtype=float)
    nonzero = full_durations[full_gaps > ZERO_BBOX_GAP_EPS].to_numpy(dtype=float)
    close = full_durations[full_gaps < NEAR_BBOX_GAP_THRESHOLD_NORM].to_numpy(dtype=float)
    separated = full_durations[full_gaps > NEAR_BBOX_GAP_THRESHOLD_NORM].to_numpy(dtype=float)
    if overlap.size and nonzero.size:
        _add_sig_bracket(ax, 1, 2, y_base + y_span * 0.05, _compare_samples(overlap, nonzero)["mannwhitney_p"])
    if close.size and separated.size:
        _add_sig_bracket(ax, 3, 4, y_base + y_span * 0.16, _compare_samples(close, separated)["mannwhitney_p"])


def plot_throughput_aggregate(summary_df: pd.DataFrame, throughput_df: pd.DataFrame, output_dir: Path) -> None:
    fig, axes = plt.subplots(2, 2, figsize=(12.0, 8.0))
    axes = axes.ravel()

    if not throughput_df.empty:
        values = throughput_df["instantaneous_saved_fps"].dropna().astype(float).to_numpy()
        medians = summary_df["save_burst_throughput_median_fps"].dropna().astype(float).to_numpy()

        ax = axes[0]
        ax.violinplot(values, positions=[1], widths=0.7, showmedians=False)
        ax.boxplot(values, positions=[1], widths=0.18, showfliers=True, medianprops={"color": "#E15759", "linewidth": 2})
        ax.set_xticks([1])
        ax.set_xticklabels(["All save bursts"])
        ax.set_ylabel("Throughput (saved frames/s)")
        ax.set_title(f"Pooled save-burst throughput (n={len(values):,})")
        ax.grid(True, axis="y", alpha=0.25)

        ax = axes[1]
        bins = min(70, max(12, int(np.sqrt(len(values)))))
        ax.hist(values, bins=bins, color="#59A14F", alpha=0.78, edgecolor="white")
        for q, label, style in zip(np.percentile(values, [25, 50, 75]), ["25th", "median", "75th"], [":", "-", ":"]):
            ax.axvline(q, color="#E15759" if label == "median" else "#555555", linestyle=style, linewidth=1.8 if label == "median" else 1.2)
        ax.set_xlabel("Throughput (saved frames/s)")
        ax.set_ylabel("Save-burst count")
        ax.set_title("Pooled throughput histogram")
        ax.grid(True, axis="y", alpha=0.25)

        ax = axes[2]
        dist = []
        labels = []
        for col, label in [
            ("save_burst_throughput_q25_fps", "25th"),
            ("save_burst_throughput_median_fps", "50th"),
            ("save_burst_throughput_q75_fps", "75th"),
        ]:
            vals = summary_df[col].dropna().astype(float).to_numpy() if col in summary_df else np.array([])
            if vals.size:
                dist.append(vals)
                labels.append(label)
        if dist:
            ax.boxplot(dist, tick_labels=labels, patch_artist=True,
                       boxprops={"facecolor": "#D7E6F5", "color": "#4C78A8"},
                       medianprops={"color": "#E15759", "linewidth": 2})
        ax.set_ylabel("Throughput (saved frames/s)")
        ax.set_title("Distribution of per-video throughput quartiles")
        ax.grid(True, axis="y", alpha=0.25)

        ax = axes[3]
        if medians.size:
            order_df = summary_df.dropna(subset=["save_burst_throughput_q25_fps", "save_burst_throughput_median_fps", "save_burst_throughput_q75_fps"]).copy()
            order_df = order_df.sort_values("save_burst_throughput_median_fps")
            x = np.arange(len(order_df))
            ax.vlines(
                x,
                order_df["save_burst_throughput_q25_fps"].astype(float),
                order_df["save_burst_throughput_q75_fps"].astype(float),
                color="#76B7B2",
                alpha=0.85,
                linewidth=3,
                label="IQR",
            )
            ax.scatter(x, order_df["save_burst_throughput_median_fps"].astype(float), s=20, color="#E15759", label="median")
            ax.legend(frameon=False)
        ax.set_xlabel("Videos sorted by median throughput")
        ax.set_ylabel("Throughput (saved frames/s)")
        ax.set_title("Per-video throughput distributions")
        ax.grid(True, axis="y", alpha=0.25)
    else:
        for ax in axes:
            ax.text(0.5, 0.5, "No throughput distribution data found", ha="center", va="center")
            ax.set_axis_off()

    fig.suptitle("Project-Level Frame Throughput", y=1.01, fontsize=13)
    fig.tight_layout()
    _save_fig(fig, output_dir, "aggregate_frame_throughput")


def plot_system_overview(summary_df: pd.DataFrame, output_dir: Path) -> None:
    fig, axes = plt.subplots(1, 3, figsize=(14.0, 4.4))

    ax = axes[0]
    x = pd.to_numeric(summary_df.get("labeling_duration_median_s"), errors="coerce")
    y = pd.to_numeric(summary_df.get("labeling_min_bbox_edge_gap_median_norm"), errors="coerce")
    ax.scatter(x, y, s=36, color="#4C78A8", alpha=0.8)
    ax.set_xlabel("Median label duration (s)")
    ax.set_ylabel("Median nearest bbox gap / frame diagonal")
    ax.set_title("Labeling time vs mask separation")
    ax.grid(True, alpha=0.25)

    ax = axes[1]
    x = pd.to_numeric(summary_df.get("saved_tracking_frames_per_anchor_label"), errors="coerce")
    y = pd.to_numeric(summary_df.get("tracking_coverage_of_video"), errors="coerce") * 100.0
    ax.scatter(x, y, s=36, color="#59A14F", alpha=0.8)
    ax.set_xlabel("Saved frames per anchor label")
    ax.set_ylabel("Video tracking coverage (%)")
    ax.set_title("Label leverage and coverage")
    ax.grid(True, alpha=0.25)

    ax = axes[2]
    vals = pd.to_numeric(summary_df.get("processing_seconds_per_video_second"), errors="coerce").dropna()
    if not vals.empty:
        ax.hist(vals, bins=min(25, max(6, int(np.sqrt(len(vals))))), color="#F28E2B", alpha=0.78, edgecolor="white")
        ax.axvline(vals.median(), color="#E15759", linewidth=1.8, label="median")
        ax.legend(frameon=False)
    ax.set_xlabel("Processing seconds / video second")
    ax.set_ylabel("Video count")
    ax.set_title("End-to-end saved-frame processing cost")
    ax.grid(True, axis="y", alpha=0.25)

    fig.suptitle("Project System Overview", y=1.02, fontsize=13)
    fig.tight_layout()
    _save_fig(fig, output_dir, "aggregate_system_overview")


def write_readme(project_dir: Path, output_dir: Path, summary_df: pd.DataFrame, aggregate_df: pd.DataFrame) -> None:
    n_videos = len(summary_df)
    def metric_value(metric: str, field: str = "median") -> str:
        rows = aggregate_df[aggregate_df["metric"] == metric]
        if rows.empty:
            return "NA"
        value = rows.iloc[0].get(field)
        if pd.isna(value):
            return "NA"
        return f"{float(value):.3f}"

    text = f"""# Aggregate System Tracking Analysis

Project: {project_dir}
Videos analyzed: {n_videos}

Core outputs:
- `per_video_system_metrics.csv`: one row per video from each video's `summary_metrics.csv`.
- `aggregate_summary_metrics.csv`: across-video summaries plus pooled per-anchor/per-save-burst summaries.
- `per_video_distribution_summaries.csv`: per-video summaries of the underlying labeling and throughput distributions.
- `pooled_labeling_timing.csv`: all anchor-label timing rows with video identifiers.
- `pooled_throughput_distribution.csv`: all save-burst throughput rows with video identifiers.
- `labeling_group_comparisons.csv`: pooled mean +/- SD, medians, Welch t-test p-values, and Mann-Whitney p-values for the bbox-gap labeling comparisons.

Key median summaries:
- Per-video median anchor labeling duration: {metric_value("labeling_duration_median_s")} s
- Pooled anchor labeling duration: {metric_value("pooled_anchor_labeling_duration_s")} s
- Pooled nearest bbox edge gap: {metric_value("pooled_nearest_bbox_edge_gap_norm")} frame diagonals
- Pooled overlapping-bbox anchor duration: {metric_value("pooled_labeling_duration_overlap_bbox_s")} s
- Pooled <0.02-gap anchor duration: {metric_value("pooled_labeling_duration_close_bbox_gap_lt_0p02_s")} s
- Per-video duration vs nearest bbox edge gap Spearman: {metric_value("labeling_duration_vs_edge_gap_spearman")}
- Per-video median save-burst throughput: {metric_value("save_burst_throughput_median_fps")} saved frames/s
- Pooled save-burst throughput: {metric_value("pooled_save_burst_throughput_fps")} saved frames/s
- Saved tracking frames per anchor label: {metric_value("saved_tracking_frames_per_anchor_label")}

Figures:
- `aggregate_labeling_efficiency.*`
- `aggregate_frame_throughput.*`
- `aggregate_system_overview.*`
"""
    (output_dir / "README.md").write_text(text)


def run(project_ref: str, output_dir: str | None = None, refresh: bool = False) -> Path:
    project_dir = Path(project_ref).expanduser().resolve()
    if not project_dir.is_dir():
        raise FileNotFoundError(f"Project directory not found: {project_dir}")
    out = Path(output_dir).expanduser().resolve() if output_dir else project_dir / "system_analysis"
    out.mkdir(parents=True, exist_ok=True)

    summary_df, labeling_df, throughput_df = load_project_tables(project_dir, refresh=refresh)
    aggregate_df, _ = write_aggregate_tables(summary_df, labeling_df, throughput_df, out)
    plot_labeling_aggregate(summary_df, labeling_df, out)
    plot_throughput_aggregate(summary_df, throughput_df, out)
    plot_system_overview(summary_df, out)
    write_readme(project_dir, out, summary_df, aggregate_df)
    return out


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("project_dir", help="Project directory containing config.json and videos/")
    parser.add_argument("--output-dir", help="Output directory. Default: <project_dir>/system_analysis/")
    parser.add_argument("--refresh", action="store_true", help="Regenerate per-video system_analysis outputs before aggregating.")
    args = parser.parse_args()
    print(run(args.project_dir, args.output_dir, refresh=args.refresh))


if __name__ == "__main__":
    main()
